### ISSUE TITLE
 tag on git everytime a new version is released

### ISSUE THREAD

**Issue by nhoudelot** [jsummers/deark#12]
Hello
it would be great if you could tag your release on git everytime you release a new version.
so that a new tar.gz would be generated on github, and.. the debian/watch file i use to check when you release a new version would work ^^

of course, it's not only for me and my little repository that it would be usefull, but for anyone that decide to check automatically when a new release is done ^^

**Comment by jsummers** [comment]
I'm thinking about it. I'll probably end up doing it, since it sounds like it would help some people.

**Comment by jsummers** [comment]
Closing old issues. Have been tagging releases for some time.
