### ISSUE TITLE
Test File samples suite?

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#13]
Deark is awesome.

Do you have a test suite of files that deark supports?
Something similar to your bmpsuite but with a file of every type that deark handles.

I'm working on a project that utilizes deark and I'm working on building up a test suite of files to automate tests against.

Thanks again for creating deark, it's really great!

**Comment by jsummers** [comment]
Much as I could use the help testing it, I don't have such a thing ready made. And it would take more time and effort than I'm willing to commit to, to put together a collection that I'm even minimally comfortable with showing to someone else. I feel bad about this, and I'm still thinking about what to do. I could probably help with selected individual formats, but I'm afraid that's about it at the moment.

(Note: As mentioned in the technical documentation, I do have a regression test system, but I'm not ready to make it public, and anyway it's pretty far from what you seem to be asking for. The goal is to catch major breakage, not test every format.)

**Comment by Sembiance** [comment]
Hey, no worries at all. I just thought that it you already had one just kicking around, I could grab it and make use of it. Don't feel bad and don't give it any more thought, it's not that important :)

Thanks again for creating deark, it's really great.
