### ISSUE TITLE
[1.5.0] Build Errors

### ISSUE THREAD

**Issue by Skibicki** [jsummers/deark#2]
Windows 8.1, MSYS2 MINGW64
deark 1.4.8 compiled successfully but 1.5.0 is showing errors.

C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-crt0_c.o): In function `main':

C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain'

collect2.exe: error: ld returned 1 exit status

make: *** [Makefile:113: deark.exe] Error 1

**Comment by jsummers** [comment]
With 1.5.0, it correctly selects the WIN32 platform, but the Makefile is not quite right for Mingw. I think the main problem is that you need the -municode link flag.

I've only tried Mingw under Cygwin, which I don't think is what you're doing. I've had success with the following shell script, which should at least give you an idea of what settings to change. Note that if you set DEARK_OBJDIR to something other than "obj", deark.exe and deps.mk will be in that directory.

```
#!/bin/bash
set -e
export DEARK_OBJDIR="mingwobj"
TOOLSPREFIX="x86_64-w64-mingw32-"
export CC=${TOOLSPREFIX}gcc.exe
export AR=${TOOLSPREFIX}ar.exe
export DEARK_WINDRES=${TOOLSPREFIX}windres.exe
export LDFLAGS="-Wall -municode"

mkdir -p $DEARK_OBJDIR/src
mkdir -p $DEARK_OBJDIR/modules
make -j4 dep
make -j4
```
I know this is not ideal.

**Comment by Skibicki** [comment]
Thank you!
You were right about -municode. Removing -municode gave the same error when building.
The build worked after removing ${TOOLSPREFIX}.  ar and windres in msys64\mingw64\bin\, don't use prefixes.
Building with '-march=native' gave a large boost to WAD file extraction and made the text output scroll smoothly.

**Comment by Skibicki** [comment]
Thank you!
You were right about -municode. Removing -municode gave the same error when building.
The build worked after removing ${TOOLSPREFIX}. ar and windres in msys64\mingw64\bin, don't use prefixes.

**Comment by jsummers** [comment]
If nothing else, I'll probably add some example build scripts to the project, including one for Mingw.
