### ISSUE TITLE
Problem with offset in PICT

### ISSUE THREAD

**Issue by ntoniazzi** [jsummers/deark#20]
Hello,
I'm trying to extract pictures from a Macintosh resource file. Most of the files contain a RECT entry like this one:

    010e 006b 0243 015a

    → top=270, left=107, bottom=579, right=346

The picture is thus 239x309 pixels. But due to the top and left offsets, only a small part of the image is visible in the bottom right corner.
Imagemagick has the same problem, but libreoffice manage to extract the correct frame.

Do you have any idea?
Thanks.

[output.019.zip](https://github.com/jsummers/deark/files/5561533/output.019.zip)

**Comment by gingerbeardman** [comment]
Can you provide an archive/download containing the file with the resource fork?

**Comment by ntoniazzi** [comment]
Here is the file with the resource fork. The example from above is taken from PICT resource 128.

[pictures.zip](https://github.com/jsummers/deark/files/5567764/pictures.zip)

**Comment by gingerbeardman** [comment]
Can you please share the parent app/file/archive?

**Comment by ntoniazzi** [comment]
You can download the .sit there: https://www.macintoshrepository.org/2851-infotron

**Comment by gingerbeardman** [comment]
For reference, here's what ResEdit shows:

![Screen shot 2020-11-21 at 11 22 31](https://user-images.githubusercontent.com/49612/99876044-28b29300-2bec-11eb-8f3b-83a59b79a674.png)

![99876046-2c461a00-2bec-11eb-98f2-3b0a10c21b55](https://user-images.githubusercontent.com/49612/99876081-5992c800-2bec-11eb-9999-3fa9b82f08dd.png)

**Comment by gingerbeardman** [comment]
And Resourcer

![Screen shot 2020-11-21 at 11 35 34](https://user-images.githubusercontent.com/49612/99876523-1e45c880-2bef-11eb-99f5-195f5ebaf002.png)

![Screen shot 2020-11-21 at 11 35 37](https://user-images.githubusercontent.com/49612/99876524-1ede5f00-2bef-11eb-8814-a76a7527e008.png)

![Screen shot 2020-11-21 at 11 35 39](https://user-images.githubusercontent.com/49612/99876525-1f76f580-2bef-11eb-9f01-5fb71d5d419a.png)

![Screen shot 2020-11-21 at 11 35 41](https://user-images.githubusercontent.com/49612/99876526-1f76f580-2bef-11eb-8db3-b1ea0ed9ce3a.png)

![Screen shot 2020-11-21 at 11 35 43](https://user-images.githubusercontent.com/49612/99876528-1f76f580-2bef-11eb-9eec-c2b33828dfca.png)

![Screen shot 2020-11-21 at 11 35 44](https://user-images.githubusercontent.com/49612/99876529-200f8c00-2bef-11eb-9519-c321cdc216c3.png)

**Comment by jsummers** [comment]
Maybe I don't understand the issue, or maybe I'm not able to reproduce it for some reason.

When I convert the output.019.pict file to PNG with ImageMagick, I get a mostly-black image with part of the hat visible in the lower right corner.

When I use Deark on output.019.pict, it creates a PNG with the full picture of a dog and the "Q Software" text. That's essentially the same thing LibreOffice gives me. As far as I can tell, Deark is doing what I expect it to do with this file.

**Comment by ntoniazzi** [comment]
You are right, I didn't think about using deark to convert the pict to png after extracting it from the resource fork.
It works well then.
Sorry for wasting your time :sweat:
