### ISSUE TITLE
Invalid RSC file produces 20,963 corrupted PNGs

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#21]
When deark processes the attached [mks_50.rsc](https://github.com/jsummers/deark/files/5826158/mks_50.rsc.zip) file (unzip first) it produces 20,963 corrupted PNG files.

I don't think this file is an actual [GEM Resource File](http://fileformats.archiveteam.org/wiki/GEM_resource_file). It appears to be a [Dali image](http://fileformats.archiveteam.org/wiki/Dali) and changing it's name to mks_50.sd0 and processing with recoil/nconvert produces a valid [image](https://user-images.githubusercontent.com/81436/104844761-06fa2300-58a0-11eb-8766-22c3950d3c02.png)

I know RSC support in deark is experimental, but could it be improved to recognize that this isn't a valid RSC?

Alternatively, the RSC module should skip outputting images that have invalid dimensions. I've attached a [rsc-invalid-files.patch](https://github.com/jsummers/deark/files/5826166/rsc-invalid-files.patch.zip) that modifies modules/rsc.c checks de_good_image_dimensions_noerr() before writing files, which cuts down to output to just 251 corrupted files.

**Comment by jsummers** [comment]
Thanks. I'm preparing some fixes to make this behavior less bad.

Sometime later, I'll try to review this format, and hopefully find a better way to deal with it. It's not obvious how to figure out that we've gone off the rails.

**Comment by kollokollo** [comment]
I have stumbled upon this issue, because I created also a program, which can read and handle the GEM RSC files. (see X11Basic). And by trying to read theis file X11-Basic crashes. Thanks for the issue. I have a similar problem with that file. The crash occurs in fix_bitblk. Obviously one should have tested for a valid file before...

**Comment by jsummers** [comment]
I don't have a good answer. Maybe someone else does. Is there a formal specification somewhere that places any useful constraints on the format?

It's just a really nasty format if you want to process untrusted files. For Deark, I'm even thinking about having two RSC modes, one with arbitrary limits, that the user would have to use an option to disable.

**Comment by kollokollo** [comment]
I have solved the issue (for X11-Basic) like this: 

If the start of  any  of the tables has an offset smaller than the length of the file header and(!) the number of objects in that table is larger than zero, then the file is considered invalid. 

In detail: `
if word[0]>5 then invalid.
if word[10]>0 && word[1]<36 then invalid.
if word[12]>0 && word[2]<36 then invalid.
if word[13]>0 && word[3]<36 then invalid.
if word[14]>0 && word[4]<36 then invalid.
if word[15]>0 && word[5]<36 then invalid.
if word[16]>0 && word[8]<36 then invalid.
if word[11]>0 && word[9]<36 then invalid.
`

**Comment by jsummers** [comment]
Closing. It's not as good as it could be, but with the extra validation and limits from commit 594208d14394 and others, it's now very unlikely to make a mess like that, and if it does it won't be as bad.

**Comment by Sembiance** [comment]
Thanks @kollokollo  and @jsummers for your work on this. The fix implemented is more than adequate :) Thanks!
