### ISSUE TITLE
Why hardcoded ARFLAGS?

### ISSUE THREAD

**Issue by polluks** [jsummers/deark#23]
https://github.com/jsummers/deark/blob/6d78f9304958c8ba7d2062232b563db94013267e/Makefile#L98

https://github.com/jsummers/deark/blob/6d78f9304958c8ba7d2062232b563db94013267e/Makefile#L102

**Comment by jsummers** [comment]
Hmm. It must just be an error.

Thanks for the report. I'll fix it.

**Comment by jsummers** [comment]
Fixed by commit 1dae79162ed6.
