### ISSUE TITLE
Can't compile Deark 1.5.8 on AmigaOS4

### ISSUE THREAD

**Issue by samo79** [jsummers/deark#24]
Got a breakage while trying to compile the latest Deark 1.5.8 on AmigaOS4 (GCC 4.2.4)

Processo: Shell 4
4.AmigaOS4:> Work:SDK/SDK/Progetti/deark-master/ 
4.Work:SDK/SDK/Progetti/deark-master> make
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/src/deark-cmd.o src/deark-cmd.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/src/deark-modules.o src/deark-modules.c
ar urcs obj/src/deark2.a obj/src/deark-modules.o
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/abk.o modules/abk.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/alphabmp.o modules/alphabmp.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/amigaicon.o modules/amigaicon.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/ansiart.o modules/ansiart.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/ar.o modules/ar.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/asf.o modules/asf.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/atari-dsk.o modules/atari-dsk.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/atari-img.o modules/atari-img.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/autocad.o modules/autocad.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/awbm.o modules/awbm.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/basic-c64.o modules/basic-c64.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/arcfs.o modules/arcfs.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/apm.o modules/apm.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/afcp.o modules/afcp.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/arc.o modules/arc.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/amiga-dsk.o modules/amiga-dsk.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/bmff.o modules/bmff.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/apple2-dsk.o modules/apple2-dsk.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/applesd.o modules/applesd.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/binhex.o modules/binhex.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/bintext.o modules/bintext.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/bmi.o modules/bmi.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/bmp.o modules/bmp.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/arj.o modules/arj.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/bpg.o modules/bpg.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/bsave.o modules/bsave.c
ar urcs obj/modules/mods-ab.a obj/modules/abk.o obj/modules/alphabmp.o obj/modules/amigaicon.o obj/modules/ansiart.o obj/modules/ar.o obj/modules/asf.o obj/modules/atari-dsk.o obj/modules/atari-img.o obj/modules/autocad.o obj/modules/awbm.o obj/modules/basic-c64.o obj/modules/arcfs.o obj/modules/apm.o obj/modules/afcp.o obj/modules/arc.o obj/modules/amiga-dsk.o obj/modules/bmff.o obj/modules/apple2-dsk.o obj/modules/applesd.o obj/modules/binhex.o obj/modules/bintext.o obj/modules/bmi.o obj/modules/bmp.o obj/modules/arj.o obj/modules/bpg.o obj/modules/bsave.o
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/cab.o modules/cab.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/cardfile.o modules/cardfile.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/cfb.o modules/cfb.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/cpio.o modules/cpio.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/d64.o modules/d64.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/drhalo.o modules/drhalo.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/ebml.o modules/ebml.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/emf.o modules/emf.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/epocimage.o modules/epocimage.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/eps.o modules/eps.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/exe.o modules/exe.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/dms.o modules/dms.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/flif.o modules/flif.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/fnt.o modules/fnt.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/gemfont.o modules/gemfont.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/gemmeta.o modules/gemmeta.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/gemras.o modules/gemras.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/gif.o modules/gif.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/grasp.o modules/grasp.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/grob.o modules/grob.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/gzip.o modules/gzip.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/hfs.o modules/hfs.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/hlp.o modules/hlp.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/dsstore.o modules/dsstore.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/fli.o modules/fli.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/fat.o modules/fat.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/flac.o modules/flac.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/ccx.o modules/ccx.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/crush.o modules/crush.c
ar urcs obj/modules/mods-ch.a obj/modules/cab.o obj/modules/cardfile.o obj/modules/cfb.o obj/modules/cpio.o obj/modules/d64.o obj/modules/drhalo.o obj/modules/ebml.o obj/modules/emf.o obj/modules/epocimage.o obj/modules/eps.o obj/modules/exe.o obj/modules/dms.o obj/modules/flif.o obj/modules/fnt.o obj/modules/gemfont.o obj/modules/gemmeta.o obj/modules/gemras.o obj/modules/gif.o obj/modules/grasp.o obj/modules/grob.o obj/modules/gzip.o obj/modules/hfs.o obj/modules/hlp.o obj/modules/dsstore.o obj/modules/fli.o obj/modules/fat.o obj/modules/flac.o obj/modules/ccx.o obj/modules/crush.o
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/misc.o modules/misc.c
modules/misc.c: In function 'de_identify_ttcomp':
modules/misc.c:2751: error: 'for' loop initial declaration used outside C99 mode
make: *** [obj/modules/misc.o] Error 1
4.Work:SDK/SDK/Progetti/deark-master>

**Comment by jsummers** [comment]
Is that the only error, or just the first one? What does "make -k" do?

If initializers in "for" statements are the only issue, I don't have a problem with not doing that.

**Comment by samo79** [comment]
Don't know if more errors will come on later files, for now it breaks at misc.c .. can you for now fixing this?
Will retry with make -k aniway :-)

**Comment by samo79** [comment]
Indeed still more, this is the output compiling with -k

4.Work:SDK/SDK/Progetti/deark-master> make -k
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/misc.o modules/misc.c
modules/misc.c: In function 'de_identify_ttcomp':
modules/misc.c:2751: error: 'for' loop initial declaration used outside C99 mode
make: *** [obj/modules/misc.o] Error 1
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/iccprofile.o modules/iccprofile.c
modules/iccprofile.c: In function 'typedec_tagArray_tagStruct':
modules/iccprofile.c:296: error: 'for' loop initial declaration used outside C99 mode
make: *** [obj/modules/iccprofile.o] Error 1
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/icns.o modules/icns.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/id3.o modules/id3.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/ico.o modules/ico.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/iff.o modules/iff.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/ilbm.o modules/ilbm.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/insetpix.o modules/insetpix.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/iptc.o modules/iptc.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/jbf.o modules/jbf.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/jovianvi.o modules/jovianvi.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/jpeg.o modules/jpeg.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/lha.o modules/lha.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/j2c.o modules/j2c.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/ogg.o modules/ogg.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/olepropset.o modules/olepropset.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/iso9660.o modules/iso9660.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/macbinary.o modules/macbinary.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/macrsrc.o modules/macrsrc.c
modules/macrsrc.c: In function 'finalize_icns_streams':
modules/macrsrc.c:155: error: 'for' loop initial declaration used outside C99 mode
make: *** [obj/modules/macrsrc.o] Error 1
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/macpaint.o modules/macpaint.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/makichan.o modules/makichan.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/mbk.o modules/mbk.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/mp3.o modules/mp3.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/mscompress.o modules/mscompress.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/msp.o modules/msp.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/nokia.o modules/nokia.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/os2bmp.o modules/os2bmp.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/ole1.o modules/ole1.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/officeart.o modules/officeart.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/lbr.o modules/lbr.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/megapaint.o modules/megapaint.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/nie.o modules/nie.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/isz.o modules/isz.c
modules/isz.c: In function 'de_run_is_z':
modules/isz.c:318: error: 'for' loop initial declaration used outside C99 mode
make: *** [obj/modules/isz.o] Error 1
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/os2ea.o modules/os2ea.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/psd.o modules/psd.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/palmbitmap.o modules/palmbitmap.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/palmpdb.o modules/palmpdb.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/pcpaint.o modules/pcpaint.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/pcx.o modules/pcx.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/pff2.o modules/pff2.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/pict.o modules/pict.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/pkfont.o modules/pkfont.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/png.o modules/png.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/pnm.o modules/pnm.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/portfolio.o modules/portfolio.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/printptnr.o modules/printptnr.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/packdir.o modules/packdir.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/pack.o modules/pack.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/printshop.o modules/printshop.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/psf.o modules/psf.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/psionapp.o modules/psionapp.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/psionpic.o modules/psionpic.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/pcf.o modules/pcf.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/plist.o modules/plist.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/qtif.o modules/qtif.c
ar urcs obj/modules/mods-pq.a obj/modules/psd.o obj/modules/palmbitmap.o obj/modules/palmpdb.o obj/modules/pcpaint.o obj/modules/pcx.o obj/modules/pff2.o obj/modules/pict.o obj/modules/pkfont.o obj/modules/png.o obj/modules/pnm.o obj/modules/portfolio.o obj/modules/printptnr.o obj/modules/packdir.o obj/modules/pack.o obj/modules/printshop.o obj/modules/psf.o obj/modules/psionapp.o obj/modules/psionpic.o obj/modules/pcf.o obj/modules/plist.o obj/modules/qtif.o
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/riff.o modules/riff.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/rosprite.o modules/rosprite.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/rpm.o modules/rpm.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/rsc.o modules/rsc.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/shg.o modules/shg.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/spectrum512.o modules/spectrum512.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/sunras.o modules/sunras.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/t64.o modules/t64.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/tar.o modules/tar.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/tga.o modules/tga.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/tiff.o modules/tiff.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/tim.o modules/tim.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/tivariable.o modules/tivariable.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/unsupported.o modules/unsupported.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/vort.o modules/vort.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/wad.o modules/wad.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/wmf.o modules/wmf.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/wpg.o modules/wpg.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/wri.o modules/wri.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/xface.o modules/xface.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/stuffit.o modules/stuffit.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/sis.o modules/sis.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/sauce.o modules/sauce.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/xfer.o modules/xfer.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/zip.o modules/zip.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/zoo.o modules/zoo.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/rodraw.o modules/rodraw.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/unifont.o modules/unifont.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/modules/rm.o modules/rm.c
ar urcs obj/modules/mods-rz.a obj/modules/riff.o obj/modules/rosprite.o obj/modules/rpm.o obj/modules/rsc.o obj/modules/shg.o obj/modules/spectrum512.o obj/modules/sunras.o obj/modules/t64.o obj/modules/tar.o obj/modules/tga.o obj/modules/tiff.o obj/modules/tim.o obj/modules/tivariable.o obj/modules/unsupported.o obj/modules/vort.o obj/modules/wad.o obj/modules/wmf.o obj/modules/wpg.o obj/modules/wri.o obj/modules/xface.o obj/modules/stuffit.o obj/modules/sis.o obj/modules/sauce.o obj/modules/xfer.o obj/modules/zip.o obj/modules/zoo.o obj/modules/rodraw.o obj/modules/unifont.o obj/modules/rm.o
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/src/fmtutil-miniz.o src/fmtutil-miniz.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/src/deark-util.o src/deark-util.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/src/deark-data.o src/deark-data.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/src/deark-zip.o src/deark-zip.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/src/deark-tar.o src/deark-tar.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/src/deark-png.o src/deark-png.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/src/deark-dbuf.o src/deark-dbuf.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/src/deark-bitmap.o src/deark-bitmap.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/src/deark-char.o src/deark-char.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/src/deark-font.o src/deark-font.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/src/deark-ucstring.o src/deark-ucstring.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/src/fmtutil.o src/fmtutil.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/src/fmtutil-cmpr.o src/fmtutil-cmpr.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/src/fmtutil-advfile.o src/fmtutil-advfile.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/src/fmtutil-zip.o src/fmtutil-zip.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/src/fmtutil-fax.o src/fmtutil-fax.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/src/fmtutil-lzh.o src/fmtutil-lzh.c
src/fmtutil-lzh.c: In function 'huffman_record_len_for_range':
src/fmtutil-lzh.c:738: error: 'for' loop initial declaration used outside C99 mode
make: *** [obj/src/fmtutil-lzh.o] Error 1
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/src/fmtutil-lzw.o src/fmtutil-lzw.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/src/fmtutil-huffman.o src/fmtutil-huffman.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/src/deark-user.o src/deark-user.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/src/deark-unix.o src/deark-unix.c
gcc -g -O2 -Wall -Wextra -Wmissing-prototypes -Wformat-security -Wno-unused-parameter -Isrc -c -o obj/src/deark-win.o src/deark-win.c
make: Target `all' not remade because of errors.
4.Work:SDK/SDK/Progetti/deark-master>

**Comment by jsummers** [comment]
Should be addressed by commit 4d03828c4c71.

**Comment by samo79** [comment]
Yes everything is ok now, you can close the ticket :-)
Thank you
