### ISSUE TITLE
graspgl module produces rainbow images

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#25]
I've encountered some graspgl .GL files that when extracted with deark produces images that are all distorted with rainbow colors. Is this something that can be improved?

Here are 3 files that produce messed up rainbow images.
**WARNING! Files are adult in nature and 100% NSFW:**
https://telparia.com/fileFormatSamples/archive/grasp/butt.gl
https://telparia.com/fileFormatSamples/archive/grasp/beachbal.gl
https://telparia.com/fileFormatSamples/archive/grasp/bunny2.gl

I can provide more files if needed.

**Comment by jsummers** [comment]
Unfortunately, the PC-Paint files in a GL animation are sometimes scripted to use a palette from a different file. The same image could probably even use multiple different palettes.

I assume the "pload" commands in the .txt script tell which files contain the palettes, and when processing the PC-Paint file, you can tell Deark which palette file to use with the "-file2" option.

Making it work automatically would be nice, but I don't really see a good, not-too-difficult way to do that.

**Comment by Sembiance** [comment]
This makes total sense! That's certainly something that I should handle outside of deark, when converting the individual GL frames.

Thanks for the info!
