### ISSUE TITLE
Support DL frame extraction

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#26]
Would be awesome if dexvert could support the extraction of individual frames from the DL animation format.

Currently I'm not aware of any modern programs that support this format (except GraphicConverter for Mac)

Info about the format, including links to old code that can load/extract the format and sample files: http://fileformats.archiveteam.org/wiki/DL

**Comment by jsummers** [comment]
Thanks for the suggestion. I'm looking into it.

If the graphics and sound resources can be usefully extracted, I'd like to at least do that.

I might try to render each frame, if it's easy enough, though that's really a job for video software like FFmpeg.

**Comment by Sembiance** [comment]
I think just extraction of the frames, like the GL module does, is plenty sufficient.
I believe I read somewhere that the individual frames are embedded TIFF files, but I don't remember where I read that and I can't 
seem to locate that info anywhere, so I may be wrong on that.

**Comment by jsummers** [comment]
I've done what's easy to do, which is to indiscriminantly extract all the images, supporting v1 and v2 format.

I'd like to also support version 3 in some way, but I don't yet know how realistic that will be.

If you have an example of a v2 "large format" file, that still needs to be tested. That's files that start with 0x02 0x00.

**Comment by Sembiance** [comment]
Awesome!

I can confirm that it works GREAT for all these samples: https://telparia.com/fileFormatSamples/video/dl/

It didn't handle the single version 3 file (xcol6.dl) of course.

I can provide additional file samples, of any version, if you need.

If v3 support is not in the cards, feel free to close this issue, as the support you've added to deark for v1 and v2 is great!!

**Comment by jsummers** [comment]
Version 3 is supported now, though it works a little differently, because the images don't necessarily correspond to whole frames.

**Comment by Sembiance** [comment]
Just tested version 3 support on a few v3 files, worked great!

I REALLY appreciate the fact that you added DL support.

Let me know if there is anything I can ever do for you.

Thanks again.
