### ISSUE TITLE
Support Video Master format frame extraction

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#27]
The "Video Master" film file format does not appear to have any modern converters.

It looks like a straightforward format, full details of the file format including samples: http://fileformats.archiveteam.org/wiki/Video_Master_Film

Is it possible for deark to support extracting each individual frame as an image?

**Comment by jsummers** [comment]
Thanks for the idea.

I haven't decided if it's worth pursuing. It doesn't look like a great fit for Deark -- what we should want is a converter, not a frame extractor. But if it turns out to be easy enough, maybe.

**Comment by jsummers** [comment]
I've added rudimentary support for this (commit 2336f3ffcae5).

**Comment by Sembiance** [comment]
AWESOME! It works great, just tested it on my sample files.

Thanks so much for adding support for it!! I areally appreciate it!!!
