### ISSUE TITLE
[FR] Add `--background-color` option 

### ISSUE THREAD

**Issue by NightMachinary** [jsummers/deark#28]
I use a light-themed terminal, so my tools output colors suited to a light background. I like to set the background of the output PNG to white.

**Comment by jsummers** [comment]
Sorry, but I don't understand. Can you give an example of what that would do? Do you mean the PNG "bKGD" chunk, or something else?

Generally speaking, for the case of converting other bitmap image formats to PNG, I don't want to add attributes to the PNG image, if they aren't in the original file.

**Comment by jsummers** [comment]
Closing - Not enough information.
