### ISSUE TITLE
Feature request: extract multiple levels

### ISSUE THREAD

**Issue by mabam** [jsummers/deark#29]
Hi there!

I just discovered Deark today and it does a great job for my use case. Thank you very much!

Do you think there’s a chance that you add the possibility to extract an image embedded at a deeper level at once?

What I came across is an old Mac PICT file containing QTIF data that again contains JPEG data. In order to extract that I have to run Deark twice. Especially for automation purposes it would be easier if I only had to issue one command.

**Comment by jsummers** [comment]
I'm not sure if you're suggesting extracting both the .qtif and the .jpg file, or just the .jpg file. For Deark as a whole, either of those things would be too big a paradigm change for me to consider casually. (For "both", there is scripts/deark-recursive.pl, though it's badly in need of an update.)

However, Deark has a number of command-line options that affect the extract-vs.-decode decision in special cases, and I think it would be good to have one for PICT/QTIF. I think the QTIF module already has the ability to process PICT data directly, so all I have to do is decide when to enable it. The main problem is that there are some QTIF compression types, e.g. "rpza", that can't be handled in any way other than putting them in a .qtif file. I'll have to think about what the logic should be.

**Comment by mabam** [comment]
Thanks for pointing me to scripts/deark-recursive.pl, that’s quite handy. However, due its automatic file naming which doesn’t reflect the original name, it is not suitable in our particular use case.

We wrote an AppleScript that takes PICT data stored on the clipboard by an emulator such as SheepShaver. It then tries to convert (or rather “extract”) the core image out of the PICT (and any subsequent) container using Deark to make it accessible on the host Mac.

For reference, here’s the snippet that automates repeated image extraction until the lowest level is reached:
```
set sourceExtension to "pct"
repeat
	set dearkResponse to paragraph -1 of (do shell script dearkPath & " -l -maxfiles 1 ~/Documents/clipboardConvFile." & sourceExtension)
	if dearkResponse is "No files found to extract!" then
		exit repeat
	else
		set destExtension to word -1 of dearkResponse
	end if
	do shell script dearkPath & " ~/Documents/clipboardConvFile." & sourceExtension & " -t ~/Documents/clipboardConvFile." & destExtension
	set sourceExtension to destExtension
end repeat
```

In most cases the resulting file is in a format compatible with macOS and is then processed by another part of the script that puts it back on the clipboard.

**Comment by jsummers** [comment]
I've added an option, "-opt pict:decodeqt", to try to bypass the .qtif step. (commit 45ca5bb72bf0)

**Comment by mabam** [comment]
Wow!
I’ve just tested it and it works as advertised. Thank you for your efforts!

One thing I just realised: If the PICT is opened and copied (cmnd-C) in PictureViewer within SheepShaver and AppleScript on the host has read it from the clipboard and written to a PICT file again, Deark can successfully extract its content. This is what we want to be able to with our script so we are completely happy with that.

But if, in SheepShaver, I open the folder containing the original file and drag that file to a shared volume on the host, when trying to process it Deark reports: “Error: Unknown or unsupported file format”, no matter whether I use “-opt pict:decodeqt” or not.

As already mentioned, this is not an issue for us in our use case. I just thought you might be interested in it as it could help improving Deark. In case you are: Find “Example Picture jsummers.zip” at [https://c.web.de/@337526389169198226/VB2C-gCgS-CZgXcmqqUaYA](url). It contains the original file, one pasted version _with_ and one _without_ a header. The latter ones work fine, the former, original one doesn’t.

**Comment by jsummers** [comment]
Your "Example Picture original.pct" file is in QTIF format, not PICT format. QTIF is hard to identify. I might try to improve it, but currently, you'd either have rename the file to end in ".qtif", or use "-m qtif".

**Comment by mabam** [comment]
Ah, I didn’t know that. So Classic Mac OS in SheepShaver wraps the QTIF in a PICT header when copying to the clipboard. As that’s the workflow we use don’t have to deal with manually identifying the QTIF.

But anyway, thanks for sharing your expertise!

**Comment by jsummers** [comment]
For various reasons, I don't have any plans to make Deark do recursive extraction. Using a script like yours, or the one mentioned early on this page, is what I'd expect. Your script doesn't use or mention the -extrlist option, so I want to make sure you're aware of it. But I don't have any other suggestions.

**Comment by gingerbeardman** [comment]
I wasn't aware of that! I guess I missed it not being in the -h help and of course #4
