### ISSUE TITLE
Hi-resolution Palm bitmap support?

### ISSUE THREAD

**Issue by gingerbeardman** [jsummers/deark#3]
Thanks for this useful utility! It rocks

files: [hana_hi.lzh.zip](https://github.com/jsummers/deark/files/3104753/hana_hi.lzh.zip)
target file: hana_kai.prc

this app is written to target Hi-Res Palm OS (320x320)

deark extracts 5 bitmaps (correct)

on my palm their sizes are:
1. 50322
2. 7442
3. 16402
4. 5138
5. 52242

deark extracts the files with the correct sizes

using `-d` the first Tbmp gives me an incomplete PNG image (you should be able to see 48+4 cards) so it looks like they're outside the image canvas:
```
DEBUG: Input file: output.000.Tbmp.palm
Module: palmbitmap
DEBUG: BitmapType at 0, len≤50322
DEBUG:  bitmap header at 0
DEBUG:   bitmap version: 2
DEBUG:   dimensions: 320×154
DEBUG:   rowBytes: 320
DEBUG:   bitmap flags: 0x4000 (hasColorTable)
DEBUG:   pixelSize: 8
DEBUG:   bits/pixel: 8 (based on pixelSize field)
DEBUG:   nextDepthOffset: 0 (none)
DEBUG:   compression type: none (based on flags)
DEBUG:  color table at 16
DEBUG:   number of entries: 4096
Warning: Invalid or unsupported type of color table
DEBUG:  image data at 16402
Warning: Not enough data for image
Writing output.000.png
```
![output 000](https://user-images.githubusercontent.com/49612/56527051-00ad0a80-6545-11e9-9887-01c2403757f3.png)

and the others are reported as corrupt
```
DEBUG: Input file: output.001.Tbmp.palm
Module: palmbitmap
DEBUG: BitmapType at 0, len≤7442
DEBUG:  bitmap header at 0
DEBUG:   bitmap version: 2
DEBUG:   dimensions: 80×80
DEBUG:   rowBytes: 80
DEBUG:   bitmap flags: 0x4000 (hasColorTable)
DEBUG:   pixelSize: 8
DEBUG:   bits/pixel: 8 (based on pixelSize field)
DEBUG:   nextDepthOffset: 0 (none)
DEBUG:   compression type: none (based on flags)
DEBUG:  color table at 16
DEBUG:   number of entries: 4096
Warning: Invalid or unsupported type of color table
Error: Unexpected end of file
```

You're not alone! I have yet to find any tools, native Palm or otherwise, that will view/extract these images. The PNG from deark is the closest yet - I can see some cards!

**Comment by jsummers** [comment]
The image's color table has "4096" colors, where 4096 is a special code, but I don't know what the code means. The table actually has 256 colors.

And, because this format kinda sucks, you have to know the exact size of the color table in order to locate the image.

Your images look okay to me if I interpret "4096" to mean 256. I'll change the logic to do that.

**Comment by gingerbeardman** [comment]
Oh! Great. 

Maybe these are Sony-specific hi resolution bitmaps? I'll look into that.

**Comment by gingerbeardman** [comment]
Works great, thanks!
