### ISSUE TITLE
Add Windows Clipboard image support

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#34]
It would be awesome if deark supported extracting/convertering images from the Windows Clipboard file format: http://fileformats.archiveteam.org/wiki/Windows_clipboard

Even though both XnView and IrfanView claim they can handle images from windows clipboard files, the sample files on the page above fail to convert properly. Seems there are some slightly different versions of bitmap/image in different versions of clipboard files.

**Comment by jsummers** [comment]
I'd like to support Clipboard/Clipbook format, but I've been putting it off, because it's hard to do well. For all I know, the format could be different in every old version of Windows, and I'm not aware of any documentation, or a good collection of sample files.

I could probably _some_ of the versions and data types pretty easily, but I need to think about whether that would be a good thing.

**Comment by jsummers** [comment]
I'm working on this.

I suspect that non-DIB "CF_BITMAP" images in these files are not necessarily portable. But I can at least make some of them work.

**Comment by Sembiance** [comment]
> I'm working on this.

That's great news! Any level of support of the various sample files would be a gret addition to deark. One way to procure more sample files would be to load up Windows 3.1, Windows 95, Windows 98 and Windows 2000 and in each open their respective `clipbrd.exe` programs and save a CLP file.

**Comment by jsummers** [comment]
Initial CLP support is in commit 65c2a1f29260.

My main concern with CF_BITMAP is that the format might depend on the video hardware & drivers & screen mode.

**Comment by Sembiance** [comment]
Just checked it out, works GREAT on all the sample files I'm aware of. Totally understand what you mean about how the image might be based on original hardware/drivers/screen mode, but what you've added is better than nothing. Thank you very much!
