### ISSUE TITLE
PC Storyboard Screen Capture Format

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#39]
I've encountered several 'Storyboard' screen captures out in the wild that have no known converter program.

It would be awesome if support for this format could be added to deark.

Attached in [storyboardPicsAndProgram.zip](https://github.com/jsummers/deark/files/7966920/storyboardPicsAndProgram.zip) are 11 .PIC files (warning some are NSFW) and an SBLIVE directory that has viewer programs that run in DOSBOX.

The .PIC files are identified by SBLIVE/PICTYPE.EXE as `PC Storyboard format: 320x200 4 color mode`

They can be opened and viewed with SBLIVE/PM.EXE

I'm not so great at reverse engineering, but it seems that this format must be fairly straight forward.

**Comment by jsummers** [comment]
Thanks, I'll look into the format at some point.

**Comment by jsummers** [comment]
I've added basic support for the format (commit 405a4f9c0e).

**Comment by Sembiance** [comment]
I've tested the new deark against **all** the files that I had discovered in the wild and they all convert perfectly!

Thanks so much!

deark is truly awesome!
