### ISSUE TITLE
CD-I IFF IMAG image support

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#40]
The CD-I format of the 90s (also used for Photo CDs) used the standard `IFF` file format for many supporting files.

One is the `IMAG` format documented here: http://www.icdia.co.uk/authoring/IFF.docs.pdf

Source code for parsing this format is available here: https://github.com/HoldcroftJ/os9_68k_sdk_v12/blob/master/SRC/MAUI/DEMOS/LIBSRC/IFF/iff_imag.c

Despite it having `IHDR` and `IDAT` chunks, these are NOT the same as PNG.

There is **no known viewer or converter** for this image type.

It would be AWESOME if deark could support this image format, as it would be the first software to do so.

Sample files are available here: https://telparia.com/fileFormatSamples/image/cdiIFFImage/

**Comment by jsummers** [comment]
Interesting. My concern is that it has 10 different color/compression types. I think that supporting the whole format isn't going to happen anytime soon, if I have to do the research.

I might try to support a subset of it, but even the three color types represented in your sample files might be difficult. For one thing, I don't know what the images are supposed to look like.

**Comment by Sembiance** [comment]
There is a CD-I emulator here: https://www.cdiemu.org/
I imagine the author would have had to tackle this format in full.

Unfortunately it's closed source.

Perhaps we could reach out to the author (cdifan@gmail.com) or post something to the forums: http://www.cdinteractive.co.uk/forums/cdinteractive/viewforum.php?f=12

**Comment by Sembiance** [comment]
Oh, looks like there have been a couple different CD-I emulator approaches: http://emulation.gametechwiki.com/index.php/Philips_CD-i_emulators

**Comment by Sembiance** [comment]
Someone has reverse engineered the color palette for one of the format samples: http://fileformats.archiveteam.org/wiki/CD-I_IFF_IMAG

**Comment by jsummers** [comment]
Well, I think the format is adequately documented already. I'm just not sure it's worth spending much time on, due to the combination of obscurity, difficulty, and lack of diverse sample files.

I'll go ahead and add support for parsing the format, and "model" 6 (IFF_MDL_CLUT4) images. But that only covers two of your sample files: 00000_FORM.iff & introbut.4c4. Every other model is more difficult, for one reason or another.

**Comment by Sembiance** [comment]
I tried out the new support, and almost all of the sample files I have convert. Awesome!

The only ones that don't are:
https://telparia.com/fileFormatSamples/image/cdiIFFImage/intro_n.4dy
https://telparia.com/fileFormatSamples/image/cdiIFFImage/intro_p.4dy
https://telparia.com/fileFormatSamples/image/cdiIFFImage/INTRO_N.6DY
https://telparia.com/fileFormatSamples/image/cdiIFFImage/intro_p.6dy

**Comment by jsummers** [comment]
I tried to figure out the remaining (DYUV) format, and came up with the attached image. The other sample images are of the same scene, with only minor differences.

Question is, are the colors reasonably close to being correct? I don't have anything to compare it to. The colors are odd, but not unbelievable.
![intro_p_6dy](https://user-images.githubusercontent.com/589239/202248798-d3f03026-8a75-4c05-aa9f-7870c3e7d176.png)

**Comment by Sembiance** [comment]
Yup, looks correct. Here is a screenshot of what the Photo-CD looks like booted up in a Philips CD-I emulator:
![screenshot_2022-11-16_15:39:45](https://user-images.githubusercontent.com/81436/202289414-951af08f-f649-4ca4-bf84-40022e04b935.png)

**Comment by Sembiance** [comment]
Looks to be all set now, just tried latest version of deark, all the files I have on hand seem to convert great.

Thanks a lot!
