### ISSUE TITLE
LZSS2 EDI Install Pro Support

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#42]
I've encountered many `EDI Install Pro` `LZSS2` compressed files out in the wild.

Examples here: https://telparia.com/fileFormatSamples/archive/ediInstallLZSS2/

I'm not aware of any utility that can decompress these. It would be awesome if deark could decompress these files.

I found some LZSS2 source code here: https://github.com/grepwood/liblzss
It took some massaging to get anything to compile (had to look at an earlier commit to see what they changed/broke) but I wasn't able to get it to work against my test files, but I don't think I gave it full consideration I gave up early.

I'm not sure which version of EDI Install Pro makes these, but here are versions of the program:
3.0: http://annex.retroarchive.org/cdrom/psl-v3n8//PRGMMING/WIN/INSTALLR/index.html
1.1: http://annex.retroarchive.org/cdrom/2themaxx-ww2/PROGRAMR/index.html

I wasn't able to get these to install anything useful, in terms of an unpack.exe that would work with these LZSS2 files.

**NOTE**: This is the `LZSS2` format which shouldn't be confused with the older `LZS` format:
Older LZS: https://telparia.com/fileFormatSamples/archive/ediInstallLZS/
They decompress fine with: https://github.com/Sembiance/dexvert/blob/master/qemu/win2k/data/app/UNPACK.EXE

**Comment by jsummers** [comment]
Thanks. This looks interesting enough, but I need to do more research first. And I need to either see some files in the wild, or figure out how to make them myself. Also, I'm skeptical that grepwood/liblzss uses the same format.

**Comment by Sembiance** [comment]
I found some in the wild on this CD: https://archive.org/details/The_Arsenal_Files_Arsenal_Computer
PATH: The Arsenal Files (Arsenal Computer).ISO/win-app/pa57.zip
PATH: The Arsenal Files (Arsenal Computer).ISO/win-app/pa6d1win.zip
PATH: The Arsenal Files (Arsenal Computer).ISO/win-app/pp61dwin.zip

**Comment by Sembiance** [comment]
Also found in these CDs:
https://archive.org/details/1-57176-053-9_2000_True_Type_Fonts_Clip_Art_Images_1994
1-57176-053-9_2000_True_Type_Fonts_Clip_Art_Images_1994.iso/fontutil/h278.zip

https://archive.org/details/experimental-bbs-explossion-iii
Experimental BBS Explossion III.iso/windows/cvt201.zip

https://archive.org/details/The_Wildcat_Files_2_Arsenal_Computer
The Wildcat Files 2 (Arsenal Computer).ISO/games/shidao35.zip

https://archive.org/details/Education_For_All_Ages_Arsenal_Computer
Education For All Ages (Arsenal Computer).ISO/astron/skymp20b.zip

**Comment by jsummers** [comment]
Working on this, but all evidence suggests the compression is the same as Okumura's LZSS software. You could already decompress an EDILZSS2 file using the options "-m lzss_oku -start 25".

For most EDILZSS1 files, the options would be "-m lzss_oku -start 21". Unfortunately, the author also released software named LZSSLib, which uses the same EDILZSS1 signature, but the format is different.

**Comment by Sembiance** [comment]
Oh, awesome! Nice to see that I can already extract these files with deark, by just specifying the proper offset and module. Just tested that, works great! That's good enough for me and my purposes, I appreciate your detective work!

I suppose there could be some merit in officially supporting the format in deark, as it looks like the original filename is embedded in the header of the file, so that could be used to ensure proper output filenames from deark. Either way, once again, thanks!

**Comment by jsummers** [comment]
Addressed by commit a64915065f65.
