### ISSUE TITLE
Interfaze App Extraction

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#43]
Back in 1995 a program called 'Interfaze' was used to create interactive applications. Kinda like a hypercard clone but for windows. It could show video, pictures, play audio, etc.

I've made a page about it here: http://fileformats.archiveteam.org/wiki/Interfaze
That page includes a link to a demo version of the maker program and links to sample files including a CD that used it.

I've encountered multiple CDs (12 and counting) that utilized this program to create their interactive content.

I couldn't find any other information on it, nor could I find a full release.

It would be AMAZING if the .app format could be reverse engineered enough so that the resources within it (sounds, images, videos) could be extracted. Would be awesome if deark could do this extraction. If something like this is beyond the scope of deark, feel free to close this issue.

**Comment by jsummers** [comment]
I took a quick look at this. The demo software doesn't make much sense to me. Can it even play .app files?

You might be onto something interesting, but I'm not prepared to try to figure out the format myself. If a specification turns up, then I'd like to look at it.

**Comment by Sembiance** [comment]
Haven't really found anything more about this format, so gonna just go ahead and close this issue as I don't have anymore info to help.
