### ISSUE TITLE
Palm PRC files fail to parse

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#44]
I came across some Palm PRC files that don't parse correctly with `deark -d3 -m palmrc inet-2.prc`

```
DEBUG: Input file: inet-2.prc
Module: palmrc
DEBUG: file size: 46206
Format: Palm PRC
DEBUG: header at 0
DEBUG:  name: "Inet Magazine No. 2"
DEBUG:  attributes: 0x0000 (none)
DEBUG:  version: 0x0000
DEBUG:  create date: ...
DEBUG:   ... if Mac-BE: 114377902 (1907-08-16 19:38:22)
DEBUG:   ... if Unix-BE: 114377902 (1973-08-16 19:38:22 UTC)
DEBUG:   ... if Mac-LE: 2923745542 (1996-08-24 15:32:22)
DEBUG:  mod date: ...
DEBUG:   ... if Mac-BE: 114377902 (1907-08-16 19:38:22)
DEBUG:   ... if Unix-BE: 114377902 (1973-08-16 19:38:22 UTC)
DEBUG:   ... if Mac-LE: 2923745542 (1996-08-24 15:32:22)
DEBUG:  backup date: 0 (not set)
DEBUG:  mod number: 0
DEBUG:  app info pos: 0
DEBUG:  sort info pos: 0
DEBUG:  type: "TEXt"
DEBUG:  creator: "REAd"
DEBUG:  uniqueIDseed: 0
DEBUG: PRC record list at 72
DEBUG:  nextRecordListID: 0
DEBUG:  number of records: 24
DEBUG:  [pre-scanning record list]
Error: Record 0 (at -2147483648) starts after end of file (46206)
```

I've attached them in the [inet-palm.zip](https://github.com/jsummers/deark/files/8240284/inet-palm.zip) file.

I'm not too familiar with this format, so I'm not sure if the sample files are betyond the scope of what deark supports.

**Comment by jsummers** [comment]
Your files are in ("non-resource") PDB format, not PRC format. If you use -m, it has to be "-m palmdb".

So it's working as intended. Though I don't really like the way it works. I think I'll review it, and decide if there's any reason for there to be two separate modules.

**Comment by Sembiance** [comment]
Cool, thanks for the update. Looks like PalmDOC E-book is a special format, I'll see if I can find something online that can convert to txt/PDF.
Thanks again.
