### ISSUE TITLE
IFF RGFX image support

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#47]
I've encountered a few '[RGFX](http://fileformats.archiveteam.org/wiki/RGFX)' images out in the wild. I am not aware of ANY known converter.

Full specifications, source code and sample files exist.

**Comment by jsummers** [comment]
Another format with XPK compression. I think I would regret opening the XPK can of worms. Realistically, RGFX support would have to come from something that already supports decompressing XPK.

**Comment by Sembiance** [comment]
Thanks for the info, closing as out of scope for deark.

**Comment by Sembiance** [comment]
I know this issue is pretty old, but how difficult would it be to have deark detect if `libancient.so` is installed on the system and leverage that for the decompression of the XPK data in IFF-RGFX?

By the way, here is a link to the RGFX specs: https://discmaster.textfiles.com/browse/4784/Amiga%20Plus%20CD%20-%202004%20-%20No.%2011.iso/AmiSoft/Dev/misc/iff-rgfx.lha/IFF-RGFX

**Comment by jsummers** [comment]
Well, I'm not planning to add any external dependencies like that to Deark. Never say never, but it's very unlikely.

I will look into supporting at least the 'MASH' compression scheme, which looks doable. That might suffice for the majority of RGFX files.

**Comment by jsummers** [comment]
I've implemented just enough of RGFX format to support the known files that have a Star Trek theme.

There's a known RGFX file with 'NUKE' compression, and while that might be doable, it's not worth it at this point.

If you find any more RGFX files, I'd be interested in seeing them.
