### ISSUE TITLE
DLL extacted with exe module produces garbage BMP files

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#55]
Running `deark BINDDLL.DLL` with the attached (unzip first) [BINDDLL.DLL.ZIP](https://github.com/jsummers/deark/files/10045920/BINDDLL.DLL.ZIP) file using the `exe` module yields 42 BMP files that are all various forms of static garbage like this:
![output 011](https://user-images.githubusercontent.com/81436/202831268-f1e091db-5f11-4ff7-ab03-0769bccbdf02.png)

Not sure if this is anything that can be corrected. Maybe there are no images in there and deark is being ambitious at extraction? Or maybe something else is at play?

**Comment by jsummers** [comment]
That's weird, but I don't see anything structurally wrong with the file, or anything wrong with Deark's extraction of the images. That's just what the images look like.

It could be that the software stores something other than image data in the image resources. Why it would do that, I don't know.

**Comment by Sembiance** [comment]
Ahh, gotcha. Must be something specific about this file. Thanks for looking into it.
