### ISSUE TITLE
Conversion of Psion 2-bit .PIC files produces 3-bit results

### ISSUE THREAD

**Issue by zedstarr** [jsummers/deark#57]
See attached collage:

![Psion_Deark_collage](https://user-images.githubusercontent.com/287540/223372653-f64368de-e9ea-4c33-80c6-5ba13221199f.jpg)

Original file SCREDEAR.PIC is a screenshot from a Psion Series 3a 2M ROM V3.40F (generated on-machine with Psion-Ctrl-Shift-S keypress)

The top half of the collage is an on-machine conversion from Psion .PIC to .BMP and shows the expected 2-bit result (i.e. Black/Grey/White, further converted to PNG in GIMP)
The lower half of the collage is deark's conversion of the same file which looks like 3-bits (Black/Dark-Grey/Light-grey/White)

Some pixels that should be black are rendered by deark as black whilst some are rendered as shades of grey
All(?) the grey plane pixels appear to be rendered by deark as light-grey

Attached files in SCREDEAR.zip -
collage: Psion_Deark_collage.jpg
original: SCREDEAR.PIC
deark's conversion: scredear.png

[SCREDEAR.zip](https://github.com/jsummers/deark/files/10907512/SCREDEAR.zip)

**Comment by jsummers** [comment]
Thanks for the report.

I don't have a specification for Psion PIC format that says anything about colors. I think Deark is just doing whatever XnView does.

Your information seems reasonable, so I'll probably make the change.

I'm curious as to *why* some PIC files use two different ways to encode black pixels.

**Comment by zedstarr** [comment]
Yeah, there's no concept of colour in the PIC format, as I understand it the black and grey information is stored as 2 separate bitmaps, one for each plane. The 3a LCD screen was 3 shades only black/grey/white. If a pixel is set in both black/grey planes it should be rendered as black, I'm guessing that might be what's causing the issue (random wild guess, I haven't looked at the code)
