### ISSUE TITLE
Spectrum512C artifacts

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#63]
The 3 Spectrum512C files attached [spc.zip](https://github.com/jsummers/deark/files/12929799/spc.zip) convert in deark but there are some minor pixel artifacts at the top line that do not show up when converted with recoil.

deark ![BLADE1_deark](https://github.com/jsummers/deark/assets/81436/e40ee561-fdb9-45b1-842a-d6ba6c6e9d3c)
recoil ![BLADE1_recoil](https://github.com/jsummers/deark/assets/81436/0e817288-dbcc-4779-bfcd-a9107493fab0)

deark ![BULB_deark](https://github.com/jsummers/deark/assets/81436/2f71e19b-1cdb-4cdd-b100-3f17b44b5093)
recoil ![BULB_recoil](https://github.com/jsummers/deark/assets/81436/a9e2d211-acb0-408a-8f31-70e08a5061f5)

deark ![test_deark](https://github.com/jsummers/deark/assets/81436/8699ace6-0323-4297-bb06-f06064775bff)
recoil ![test_recoil](https://github.com/jsummers/deark/assets/81436/cee1f14f-789a-4082-841c-b4d8ef86bdf5)

**Comment by jsummers** [comment]
Should be fixed now.
