### ISSUE TITLE
Problematic Spectrum 512S SPS files

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#64]
I have 3 `.SPS` files attached in [problematic_sps.zip](https://github.com/jsummers/deark/files/13603225/problematic_sps.zip) that appear to be Spectrum 512S format, but none of them convert correctly with deark, recoil2png or nconvert.

It's possible these files are corrupted or are not actually Spectrum 512S files. However on the chance that they just have a slightly different format and support can be added to deark for them, I thought I'd submit this.

**Comment by jsummers** [comment]
I don't know. I've seen at least one of these files before, but couldn't figure it out, and still can't. I may take another look at them, eventually.

It does look something like Spectrum 512-smooshed format, but maybe an unknown variant of it, or maybe the files are corrupt.

**Comment by Sembiance** [comment]
Yah, it's highly suspcious that 2 of the files are exactly 8192 bytes. Those are likely truncated files and beyond help. AI_R_010 may very well be corrupted beyond repair. I wouldn't spend much time on these.

**Comment by Sembiance** [comment]
Found 3 more files that don't convert well from the same source CD. 1 SPS and 2 SPC. [more.zip](https://github.com/jsummers/deark/files/13638243/more.zip)

**Comment by Sembiance** [comment]
I'm pretty certain that these are corrupt as I've not encountered any others, just these files.
