### ISSUE TITLE
Yanagisawa PIC2 Support

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#66]
It would be cool if deark supported Yanagisawa PIC2 images.
I've attached a bunch as [pic2.zip](https://github.com/jsummers/deark/files/14320085/pic2.zip)

I'm not aware of any modern converter that can handle them and I've encountered some of these files 'in the wild': https://discmaster.textfiles.com/search?formatid=yanagisawaPIC2

I did find this plugin for xv that claims PIC2 support: https://github.com/jasper-software/xv/blob/main/src/xvpic2.c
However I compiled it and it wasn't able to open the 2 or 3 PIC2 files I tried.

Some additional info on the file format wiki about it: http://fileformats.archiveteam.org/wiki/PIC2

**Comment by jsummers** [comment]
I'll take a look at it. If I can figure out the format, I'll probably add support for it.

**Comment by jsummers** [comment]
PIC2 uses arithmetic coding compression, which I don't have much experience with. Even if I had a PIC2 format specification, it wouldn't be worth trying to write a decompressor from scratch.

I'd have to use someone else's source code. But the only source code I know of is from xvpic2.c, which does not allow such use. I'm assuming the license given at https://www.ikemo.to/xv-jp-extension/e/ is still accurate.

So I'm kind of at an impasse.

I haven't tried to compile XV myself. Superficially, xvpic2.c looks like it ought to support all of the example files you presented.

**Comment by Sembiance** [comment]
Thanks for looking into it, I appreciate it!

I was able to locate some different source code for PIC2 loading & saving: https://discmaster.textfiles.com/browse/10329/MACPOWER-1996-09.ISO.7z/MACPOWER-1996-09.ISO/%E7%AC%AC%EF%BC%92%E7%89%B9%E9%9B%86%EF%BC%9A%E3%83%97%E3%83%A9%E3%82%B0%E3%82%A4%E3%83%B3%E5%A4%A7%E9%9B%86%E5%90%88/PIC2%20Save

Not sure if that's helpful or not.

**Comment by jsummers** [comment]
Interesting, but not easy for me to make sense of. The code was written by someone whose name is translated as "Watchdog" or "Guard Dog", and is owned by "K&M Software Corporation". I suspect it's related to the xvpic2.c code, but with a lot of slight differences in formatting and variable names. Maybe one was derived from the other, or they were both derived from some other program.

The Terms of Use of the K&M code are not very clear to me, though it looks like it might be more permissive than xvpic2.c.

I haven't decided what to do about this format. It's complex and over-engineered, and the language barrier is a problem. Maybe the next step would be to get one of the existing PIC2 programs compiled and working, but I'm not really planning to pursue that in the near future.

**Comment by Sembiance** [comment]
So there is a new image converter that now supports Yanagisawa PIC2: https://codeberg.org/kaleido/wuimg

Since there now exists a modern converter for this format and due to the complexity of implementing this format, I'm gonna go ahead and close out this issue. I appreciate that you took a look at what it would take, it was most appreciated!
