### ISSUE TITLE
RIFF MMM Extractor

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#68]
It would awesome if deark could extract the pictures from RIFF MMM files.

There are 7,683 unique MMM files [on discmaster](https://discmaster.textfiles.com/search?formatid=riffMultimediaMovie&dedup=dedup) and I'm not aware of any modern program that can extract the resources out of it.

Here is a some information about it: http://fileformats.archiveteam.org/wiki/RIFF_Multimedia_Movie
It appears to be a very early Macromedia Director format.

I came across this person's script: https://github.com/mainframed/HACKERS.EXE/blob/main/dump_rmmp.py#L54C16-L54C28

Which lead me to try and make my own extractor: https://github.com/Sembiance/dexvert/blob/master/bin/unMMM/unMMM.js

My script properly extracts strings, sounds and some other metadata, but it's the image `DIB ` files that I'm stuck on.
My script can parse out the image meta data and pixel data, but actually turning that into an actual image, is not my area of expertise so I was hoping that maybe deark could add support for the format.

I have uploaded a [mmm.tar.gz](https://sembiance.com/wip/mmm.tar.gz) that has 16 sample MMM files that I've been using to help build the extractor (more can be downloaded [on discmaster](https://discmaster.textfiles.com/search?formatid=riffMultimediaMovie&dedup=dedup)). Also in that archive I have the results of my extraction for each MMM, including the raw bitmap dib pixel data and a `meta.json` file that contains all the width, height, bits per pixel and other image for each dib.
The data has a `compression` flag and about 50% of the files have this set to `0` which I assume means no compression and 49% has it set to `1`. A small number have it set to `2`.

Anyways, it would be a truly awesome thing if deark could support these, as there is undoubtly all sorts of interesting content locked away in these files that appear to have been fairly widespread in the early CD-ROM days.

**Comment by jsummers** [comment]
I'm interested in extracting the image resources from these files, but I can't say much more than that, until I know more about the "compressed" DIB chunks. It could turn out to be fairly easy, or it could turn out to be too difficult, or unsuitable for Deark for some other reason.

Hopefully, each chunk is a self-contained image, and the compression/encoding schemes can be figured out, and we can figure out how to assign the right color palette to each image.

I already know how to decode most of the uncompressed images, though without correct colors. Even with correct colors, I'm not sure that would be very useful by itself.

I plan to work some more on this, and see if I hit any roadblocks.

**Comment by jsummers** [comment]
My first set of sample files all had one palette each, but unfortunately there are many files that have multiple palettes, and some that seem to use a palette from a different MMM file.

For example, this [bbanim.mmm](https://discmaster.textfiles.com/view/10910/ESPN_Coaching_Tips_Intellimedia_1994.iso/pc/bbanim.mmm) file has 4 images and 7 palettes. Each image has (at least) one correct palette, but there's no obvious way to figure out which is which. The sequence numbers are not enough.

So, the status is that sometimes it works, and sometimes it doesn't. I'm open to ideas for how to improve it.

**Comment by Sembiance** [comment]
That's great progress!

Looking at the win3.x code you sent, the `vwsc` chunk (movie score) references the palette, looks like that *possibly* determines when to change the palette. Not sure how to correlate that to the images though. Maybe each palette change in sequence corresponds to the same image sequence? Or maybe there is another chunk or identifier that some how tie the 2 together?

At the very least, maybe that chunk can at lest determine which palettes are being used and which ones are extra or un-used, though I'd suspect they are all used?

If that turns out to be a dead end, having an `-opt` to specify which palette number to use (default to best guess) along with outputting the number of palettes if a higher `-d#` verbosity is set.

**Comment by Sembiance** [comment]
Attached is a zip that has a KANSAS.MMM file [kansas.zip](https://github.com/jsummers/deark/files/15111904/kansas.zip)
It doesn't appear to have a palette built in, so it deark wasn't able to convert the images correctly (see deark subfolder).
I loaded the original program up on a windows box: https://discmaster.textfiles.com/browse/18271
It runs in 256 color mode and I was able to locate 2 of the pictures in the game and took screenshots of them to help you deduce what the palette might be.

**Comment by jsummers** [comment]
The shardcst.mmm file has two palettes that go with these images. One palette is a little darker than the other.

I was already planning to add an option to read the palette from a separate file. I'll get that done soon.

I want to make Deark a little better than it is now, but by itself, it's never going to be _good_ at handling this format. Ultimately, you'd probably have to start with the player .exe file (wyatt.exe in this case), and somehow trace through everything from there.

**Comment by Sembiance** [comment]
Ahh, gotcha. Don't spend too much time worrying about these edge cases, the fact that 90% of the images from MMM files seem to extract and convert ok is good enough as before deark there wasn't any way to see any of the images at all.
