### ISSUE TITLE
Installer VISE

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#74]
Discmaster has over 7,600 unique Mac Installer VISE packages and I am not aware of any program that can extract them: https://discmaster.textfiles.com/search?formatid=installerVISE&dedup=dedup

These are all technically self-extracting Mac executables however, so they can be extracted simply by running them (infinitemac.com is super useful for this). However having a tool that could extract the files from with them would be quite valuable at surfacing the content from these 7,600+ unique files in the upcoming discmaster 2.

I came across this pastebin that describes the format: https://pastebin.com/GwQYz2gG

It's a good starting point, but it's not complete and doesn't account for different versions of installer as when I investigated it against some file samples, I found some gaps/differences.

For example this package only seems to reference files already on disk: https://discmaster.textfiles.com/view/267/Bernard_of_Hollywoods_Pin-Ups.iso/mac/english/Pin_ups%20English%20Installer/Pin_ups%20English%20Installer

However this package has actual data embedded in the file itself: https://discmaster.textfiles.com/view/122/1998%20Denver%20Broncos%20Cheerleaders.iso/mac/Install/Install%20ScreenSaver/Install%20ScreenSaver

Sorting the discmaster list by size descending shows many multi-megabyte installers that clearly have their file data packed inside. It's certainly compressed in some way though, as trying to find any of the byte sequences from the files that were extracted from the installer failed.

There are certainly a ton of examples available to help reverse engineer the different installer versions, but I wonder if it may be out of scope of deark.

I know you are not much of a mac person, but on the off chance that you were feeling up for a challenge in supporting it, I thought I'd submit this issue :)

EDIT:
Located another resource on the format: https://github.com/habnabit/delvmod/wiki/Installer_VISE

**Comment by jsummers** [comment]
I'm looking at it, but I think it's beyond what I can do right now.

I'd have to learn more about Mac executable format, and figure out the compression scheme and other things. And it would probably be important to support multi-volume archives. I do have some half-formed plans to support multi-volume archives in Deark, but it's not there yet, and Vise might be particularly hard to deal with.

I see that there is a Windows version of Vise -- I assume it's a self-extracting executable format. It's supposedly supported by "InstallExplorer" Far Plugin, and derivatives of that, though I don't see any source code.

**Comment by Sembiance** [comment]
I actrually use InstallExplorer to handle the windows versions, sadly it doesn't work on the mac versions.

As for the mac version, I figured it was a long shot, but thought I'd give it a shot :)

**Comment by Sembiance** [comment]
I think due to the amount of reverse engineering work that would be needed here, I think it's probably best to close this out for now.
