### ISSUE TITLE
ThumbsUp thumbnail extractor

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#75]
A program in the 90s called ThumbsUp was used on CDs to provide the user with a way to view thumbnails of the images on the CD. It stored it's thumbnails in a `.tud` file and there was also an index file ending in `.tux`.

Examining the `.tud` I see in the first 12 bytes:
`0xBEBADABE` magic number
`uint32le` # of thumbnails
`uint32le` total size of .tud file

After that there may be some zero padding and then it looks like the thumbnail entries appear one after another. Each entry seems to have a zero terminated original filename and after that there appears to be RGB pixel values, but it's just garbled when I tried converting it. So maybe there is a palette, or maybe it's not just RGB values.

Attached is a [thumbsUp.tar.gz](https://github.com/jsummers/deark/files/15422629/thumbsUp.tar.gz) archive with 5 sample sets.

A bunch more detected here: https://discmaster.textfiles.com/search?q=tud&qfields=ext&family=unknown&sortBy=size&sortOrderDesc=desc&showItemName=showItemName

There are only 55 files on discmaster, so this isn't a very high priority format, but at first glance it may be a fairly straightforward format to extract the thumbs out of.

**Comment by jsummers** [comment]
Thanks for the idea. I'll take a look at it.

At this point I don't know if it's possible to decode the .tud file without reading the .tux file. If .tux turns out to be critical, that's okay, though inconvenient.

**Comment by Sembiance** [comment]
Awesome! Just tried it out, works great! Thanks, deark is amazing!
