### ISSUE TITLE
FM-Towns Icon File Extractor

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#76]
The FM-Towns system used an icon archive format that I'm not aware of anything that can extract/convert them.

I've attached some samples [fmtowns_icn.zip](https://github.com/jsummers/deark/files/15445606/fmtowns_icn.zip) and here are some more: [discmaster .icn fm-towns](https://discmaster.textfiles.com/search?q=icn&qfields=ext&family=unknown&itemid=3624&itemid=659&itemid=660&itemid=661&itemid=662&itemid=663&itemid=664&itemid=657&itemid=658&itemid=1146&itemid=1147&itemid=12214&itemid=12215&itemid=20&sortBy=size&showItemName=showItemName)

The `m_menu.icn` and `chihiro.icn` files look very straightforward, as loading them my hex editor I saw the icon outlines in the mini-map of the editor:
![screenshot_2024-05-25_20:31:01](https://github.com/jsummers/deark/assets/81436/5b47b44c-26d4-468b-b0ec-afcce5b90621)

That was with the mini-map showing 16 bytes across.

The `towns.icn` looked gibberish until I adjusted the mini-map width to 24 bytes and then it showed some distinct icon patterns.

I found some FM-Towns C code that does *something* with these files, but running the code against some .icn files doesn't seem to do anything, but the code references the `ICNFILE` magic number so you may be able to determine what the rest of the format of the file is by examining this code:
https://discmaster.textfiles.com/view/658/FM%20Towns%20Free%20Software%20Collection%2011.iso/taropyon/misc/devtool/icndat/icndat.c
https://discmaster.textfiles.com/view/658/FM%20Towns%20Free%20Software%20Collection%2011.iso/taropyon/misc/devtool/icndat/icncchg.c

**Comment by jsummers** [comment]
Thanks for finding that source code. I'd looked at this format before, but it seemed too complicated, and this mostly clears it up. (The source code won't work on most compilers due to portability issues, and doesn't really do anything useful anyway, but it has information about the format.)

Where I'm stuck at is colors. Most icons are 16-color, but no palettes are stored in the file. Assuming there is one standard 16-color palette, I'll probably figure it out eventually.

**Comment by Sembiance** [comment]
So I got an FM-Towns emulator running and loaded up this CD: https://discmaster.textfiles.com/browse/658/FM%20Towns%20Free%20Software%20Collection%2011.iso

Attached is a zip of screenshots of the icons, showing their colors [fmTownsFSC11_screenshots.zip](https://github.com/user-attachments/files/15685914/fmTownsFSC11_screenshots.zip)

I'm not sure how to tie which icon comes from which file, so let me know if you'd like me to emulate a different CD.

**Comment by jsummers** [comment]
Thanks for the screenshots. From that, and other screenshots from the internet, I have what I need to support the standard palette.

**Comment by jsummers** [comment]
Here's something: [.../icon/amu](https://discmaster.textfiles.com/browse/657/FM%20Towns%20Free%20Software%20Collection%2010.iso/t_os/icon/amu)

It's an ICN file, and a TIFF screenshot of the icons in it. But it's a different set of colors. Most ICN files are clearly designed for the standard palette, but a few, like these, look wrong to varying degrees.

So there's clearly more to learn, though I'm not planning to do anything more at the moment.

In addition to the main "ICNFILE" format, commit 2cb7d8952c adds limited support for the simple "CRI-FUJU/FJ2" formats, on the assumption that they use the same palette. It's kind of hard to tell.
