### ISSUE TITLE
Picture Packer support

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#77]
3 popular picture formats existed for the Atari ST called Picture Packer: http://fileformats.archiveteam.org/wiki/Picture_Packer

The only 2 modern converters that support these formats are Konvertor and abydos (which is no longer maintained and is crashes with many files).

It would be awesome if deark could support these formats. The file formats wiki has links to the Low, Med and Hi res samples and has some other links to useful info.

You can examine the abydos conversion code in [abydos-0.2.10.tar.xz](https://snisurset.net/code/abydos/files/abydos-0.2.10.tar.xz) specifically `plugins/atari/stos.c` and `plugins/atari/atarist.c`

**Comment by jsummers** [comment]
I'm going to try to support this. It's not easy to figure out, though. It has some similarity to AMOS Picture Bank, but it's not the same.

**Comment by jsummers** [comment]
Deark can now decode all five of the Picture Packer and/or STOS Packed Screen image formats. But it often doesn't detect the correct format. I'll work on that next, though I think it won't always be possible.

**Comment by Sembiance** [comment]
Awesome!

**Comment by jsummers** [comment]
I've found a 6th format, maybe only used by ".DAJ" files in packages like [this one](https://discmaster.textfiles.com/browse/22199/F030_POWER2.iso/ST_STE/MAGS/STPLUS19.ARJ/stplus19.msa/STP).

Distinguishing these formats is a real problem. For example, contrary to some reports, most "Picture Packer PP1" files do not use the ".PP1" file extension.

For now, you have to use "-opt stos:pp1", "-opt stos:pp3", or "-opt stos:m4p" to decode the nonstandard formats.

**Comment by Sembiance** [comment]
New code works great! Handles all the files I threw at it, just fine :)

Thanks so much for adding support for it. deark continues to be a great tool for preserving out digitial history.

Not sure if you are totally done, so feel free to close out this issue once you feel it's all done. Thanks again :)

**Comment by jsummers** [comment]
I think I've done about all I can easily do, as far as guessing the correct image type. It's possible to do better, but it may require high technology. Analyzing the palette to make a guess as to how many colors are significant is one idea.

Here's an example of a file where Deark still gets it wrong: [CLKNDAG1.MBK](https://discmaster.textfiles.com/view/15375/nf_archive_10.iso/MAGS/LEDGERS/LEDG_08.MSA/ARTICLES/CLKNDAG1.MBK)
