### ISSUE TITLE
GEM (PC) .RSC resource file

### ISSUE THREAD

**Issue by polluks** [jsummers/deark#8]
You have support if you change all `de_getu16be` and `de_getu32be` to little endian. The version is also zero :-(

**Comment by jsummers** [comment]
I'll look into it. If you know a good place to get sample files, that could help.

**Comment by gingerbeardman** [comment]
http://www.deltasoft.com/downloads-gemworld.htm

For example in GEM Write zip file.

http://www.retroarchive.org/cpm/archive/unofficial/download/write10.zip

**Comment by jsummers** [comment]
I added support for the little-endian format, provided the version number is 0.

If other versions exist, I need to find samples of them.
