### ISSUE TITLE
IBM Pack Archive? OS/2 PACK variant?

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#80]
I've encountered an archive format that [GT2](https://www.helger.com/gt/gt2.htm) labels as: IBM Pack Archive

All the files on this OS/2 CD in these folders, ending in `@` seem to be this format:
https://discmaster.textfiles.com/browse/216/The%20Arsenal%20Files%20(Arsenal%20Computer).ISO/os2_app/cs0054-2.dsk/FIX/CS2
https://discmaster.textfiles.com/browse/216/The%20Arsenal%20Files%20(Arsenal%20Computer).ISO/os2_app/wf2fix10.dsk/FIX/WF2

They seem to have a magic number of `0xA596FFFF` and the filename appears to be at offset 15

This is almost identical to the OS/2 Pack magic number, so I'm guessing these are a variant of OS/2 pack, perhaps an earlier/later version?

In the parent directory I found an `UNPACK.EXE` OS/2 exe that likely can handle it: https://discmaster.textfiles.com/browse/216/The%20Arsenal%20Files%20(Arsenal%20Computer).ISO/os2_app/wf2fix10.dsk

Figured you may want to take a peek at these, see if maybe they could be extracted.

**Comment by jsummers** [comment]
Interesting. I guess this is an older version of the format. Compression seem the same as the 0xa596feff version.

Deark supports it now, though probably not completely. I suspect the format has a feature (multi-file archives? extended attributes?) that these example files don't use.

**Comment by Sembiance** [comment]
Awesome! Your update seems to extract the files I linked to just fine. So I'd call this done, feel free to close if you wish :)
