### ISSUE TITLE
Pixfolio Thumbs extraction?

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#81]
A popular 'Image Catalog System' used on CD-ROMs was: Pixfolio

It created `.cat` files that I believe have thumbnails of images in them. It also created a corresponding `.cix` file which is an index file. Not sure if the index file is actually neded though as the `.cat` files seem to have the internal thumbs just one after another.

If deark could extract the thumbs from these `.cat` files, that would be awesome.

Here are some sample `.cix` and `.cat` files:
https://discmaster.textfiles.com/browse/317/Bodyshots%20(Multimedia%20Version).iso/pc/for_pc
https://discmaster.textfiles.com/browse/5670/ARCADE_1.ISO/for_pc
https://discmaster.textfiles.com/browse/17604/STRATEGY.ISO/for_pc

It may other things beyond just thumbnails. I may also be wrong about it containing thumbnails, but some of those `.cat` files are 15+MB which feels like they probably have thumbs in them.

Edit: This isn't a huge priority. These were mostly found on Aztec CD's that had all the photos in the CD too, so the thumbnails are somewhat redundant. Also there are only a few hundred of these on discmaster, not like thousands.

**Comment by jsummers** [comment]
Thanks for the idea. I'll probably add support for it. It looks pretty easy.

I've actually looked at this format before, but must have forgotten about it, or decided against studying it for some reason.

**Comment by jsummers** [comment]
The CAT format is "easy", but quirky and hard to identify. With commit b5627ed472, it works for all the files I've tested. But I bet there are some files that don't work.

**Comment by Sembiance** [comment]
Awesome! I'll give it a go and if I come across any that fail to convert, I'll let you know.
