### ISSUE TITLE
Another OS/2 PACK variant?

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#83]
Found some additional OS/2 files that may be more variants of the OS/2 PACK format: https://discmaster.textfiles.com/browse/570/OS2%20Arsenal%20v1.0%20(Disc%202)(Arsenal%20Computer).ISO/os2_drvr/ncrvid21.zip/OS2VID21.IMG

The 'unkown' files at the bottom appear to be similar to OS/2 PACK at first glance, starting with `0xA596` but then differing

**Comment by jsummers** [comment]
Thanks for finding this. It's definitely another variant of the format I'm calling OS/2 PACK.

I'll add support for it, but I wonder if the files always start with a5 96 00 14. It would be nice to find more example files.

**Comment by jsummers** [comment]
I did some testing, and the 00 14 byte sequence does seem to be a version identifier. Everything else I tried is rejected by UNPACK.

Closing (completed).
