### ISSUE TITLE
FM-TOWNS CRI-FJ2 Failed File

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#85]
Found a fm-towns icon CRI-FJ2 varient file that deark isn't able to handle: https://discmaster.textfiles.com/view/660/FREESOFT.BIN/gear/matusita/disk_a.exe/ICON.ICN

**Comment by jsummers** [comment]
Thanks.

The file seems to have a mismatch between the reported number of icons (53), and the actual number (52). I don't know if that's valid, but I've changed Deark to be tolerant of it.
