### ISSUE TITLE
3DFX Image Format

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#86]
Back in the VooDoo card days, a popular 'texture/image' format was the 3DFX Glide `.3df` format. I am not aware of any modern tool that is able to convert these.

I found this newsgroup post from 1999 that gives a quick overview of the format:
https://groups.google.com/g/comp.graphics.api.opengl/c/DOyoes__iVQ?pli=1

3DFX provided a Glide tool called `texus` that can convert these to TGA. The code was open sourced at some point and the code is available here:
https://github.com/Danaozhong/3dfx-Glide-API/tree/master/swlibs/texus2/lib

Unfortuantely I wasn't able to get it to compile yet under linux. Luckily I tracked down a compiled .exe version that works under wine: https://discmaster.textfiles.com/view/22850/PCA0498.ISO/Demos/RoboR/_robo.EXE/DATA/TXT/TEXUS.EXE

There are thousands and thousands of these files on discmaster so adding support for it in deark would be a cool thing to have since I'm not aware of any other converter other than the old texus tool.

Samples can be found at: https://sembiance.com/fileFormatSamples/image/glide3DFXTexture/
Also the github repo above has serveral 'test' files scattered in various directories, they likely cover more edge cases in case you decide to add support for this image format.

**Comment by jsummers** [comment]
Thanks for the suggestion. Some of the files do look pretty simple, but I'm leaning toward not trying to implement it, at least not anytime soon. I think there are just too many image types, and associated data, that I'd have to figure out. And the Texus software already exists -- hopefully someone can figure out how to get it to compile and work.

**Comment by Sembiance** [comment]
No worries, sounds good, thanks for taking a look! :)
