### ISSUE TITLE
NewIcons - Problematic Files

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#87]
I came across some Amiga NewIcons files that convert with a messed up colors. I've attached them as [newIcons.zip](https://github.com/user-attachments/files/16648837/newIcons.zip)

When I loaded these in an emulated Amiga, they looked just like how deark converts them, with messed up colors.
However when I loaded them in AROS, they looked ok, so I took some screenshots of the icons as how the original author of the icons intended them to look and included them in the zip.

NOTE: I just took a screenshot of the emulated window and tried to crop to just the icon with gimp, but I'm not certain the emulator was running with the correct pixel ratio or whatnot.

**Comment by jsummers** [comment]
Thanks for the images, and the screenshots.

The images are weird. 257 colors, 9-bits per pixel. But they seem to be basically well-formed.

None of your example files actually use the 257th color, and it would take some extra coding to support that. I'm happy to do it if such an image turns up, but until then, it's not worth it.

With commit a12ae510239f, the example files should work.

**Comment by Sembiance** [comment]
Just tested it against several hundred icons that were messed up, they all convert ok now! Thanks!
