### ISSUE TITLE
Inno Setup Archive

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#89]
A popular setup program was Inno Setup. While a bit more modern, would be awesome to have support for extracting them in deark.

Example files (and the other `setup-#.bin` files): http://discmaster.textfiles.com/view/6096/UFO_OfficeGames_DVD.iso/setup-1.bin

Looks like the Inno Setup source code was released under a very open license, so this code might offer some clues as to the format of the 'archive' format: https://github.com/jrsoftware/issrc/blob/b67d1e436309a178ce9b20d54c64865e4fff2f69/Projects/Src/Shared.Struct.pas

Also someone else wrote an extractor in Java for a very specific game that appears to use Inno Setup format: https://github.com/d0k/ednaunpack/blob/fd3b05c453382a28a641df10ec211480da14a6b2/Slice.java

**Comment by jsummers** [comment]
Thanks for the idea. But, for various reasons (need to support multi-part archives, probably need to parse the setup.exe file, maybe need to decompress LZMA in some cases, ...), it's probably not something I'll get to in the foreseeable future.

**Comment by Sembiance** [comment]
Ahh no worries, that does sound more involved than I had hoped it may be. Thanks for considering it!
