### ISSUE TITLE
clang raises error due to uint redefinition

### ISSUE THREAD

**Issue by mistydemeo** [jsummers/deark#9]
When compiling deark 1.5.4 on macOS, I get the following error:

```
In file included from src/deark-unix.c:20:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/types.h:92:33: error: cannot combine
      with previous 'int' declaration specifier
typedef unsigned int            uint;           /* Sys V compatibility */
                                ^
src/deark.h:55:23: note: expanded from macro 'uint'
#define uint unsigned int
                      ^
```

This comes from the `#define` added in 018c79b89adf30fb2eb4cbab87e7bb1c423b519d; macOS's `sys/types.h` already includes a `uint` definition, which clashes with this `#define`. Switching it to `typedef unsigned int uint;` resolves the issue.

**Comment by jsummers** [comment]
Thanks. I would think a typedef is *more* likely to cause conflicts than a macro is, even if it works in your case. I think the real problem is a bad #include order. I might try changing it to a typedef, anyway.

**Comment by jsummers** [comment]
Assuming this issue is obsolete. (Not using uint anymore.)

**Comment by mistydemeo** [comment]
Thanks!
