### ISSUE TITLE
Problematic TGA file

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#90]
Found a TGA file that I'm not sure deark is converting properly. In the [https://sembiance.com/wip/problematicTGA.zip](https://sembiance.com/wip/problematicTGA.zip) file (was too big to attach to issue) is the `original.tga` what `deark.png` creates and `good.png` which is what I think it should probably look like?

**Comment by Sembiance** [comment]
Ahh interesting indeed.

I tried 18 different converter programs and 7 of them show the starfield background image. These 7 progams are older, from the DOS/Windows 95/Windows XP era.

The other 11 more modern programs all show it as transparent like deark.

Here are some other example TGA's where this *odd trick* was used with a background image:
[mp2_marine_zodiac_birds_high.tga](https://discmaster.textfiles.com/file/18897/Xbox%20-%20X03%20Media%20Resource%20-%2016-17%20September%202003%20(USA).iso/data/Games/3rd%20Party/Ubisoft/GRIT/Artwork/Artwork.zip/mp2_marine_zodiac_birds_high.tga) (converted with background as [mp2_marine_zodiac_birds_high.png](https://sembiance.com/wip/mp2_marine_zodiac_birds_high.png))

[EverQuest2_screen5_house.tga](https://discmaster.textfiles.com/file/18717/Ubisoft%20E3%202004%20Press%20Kit%20(USA)%20(En,Fr,De,Es,It)%20(Disc%202).bin/UBISOFT%20EUROPE%20ONLY%20GAMES/EverQuest%20II%20-%20EUROPE%20ONLY/SCREENSHOTS/EverQuest2_screen5_house.tga) (converted with background as [EverQuest2_screen5_house.png](https://sembiance.com/wip/EverQuest2_screen5_house.png))

[banner4.tga](https://discmaster.textfiles.com/file/23212/Gamestar_61_2004-04_dvdb.iso/DVDStar/Akce/Q3A/Fortress/q3f_230_public-beta.zip/q3f2/q3f2_pak3.pk3/textures/q3f_hunted/banner4.tga) (converted with background as [banner4.png](https://sembiance.com/wip/banner4.png))

[outsiders.tga](https://discmaster.textfiles.com/file/18815/Rockstar%20+%20Take-Two%20Interactive%20(USA).bin/MTM%2064/Truck%20Renders/outsiders.tga) (converted with background as [outsiders.png](https://sembiance.com/wip/outsiders.png))

Some of them really relied on this for the image to even make sense such as the EverQuest house. So there seems to be a period of time where various artists used this 'hack' and expected it to work out in the wild.

**Comment by jsummers** [comment]
Your examples aren't necessarily the same in detail, but it seems like the same general idea: Use the alpha/attributes channel to make an image that can be rendered in two different ways.

I've added an option to disable transparency, but it isn't going to help much with this type of thing.

**Comment by Sembiance** [comment]
I think the option you added is the best way to handle these and it works for my use case. Just tested it out, works great. Thanks for adding it. Appreciate deark a lot!
