### ISSUE TITLE
Print Shop GS graphics

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#92]
Would be awesome if deark could support converting Print Shop GS graphics from the Apple IIgs as there are thousands of them out in the wild.

The Print Shop GS was a program available on the Apple IIgs and it came with a bunch of graphic images you could use. Softdisk G-S was a disk magazine, over 160 issues were made and many of the disks included more Print Shop GS graphics. Several bonus graphics packs were sold commercial as well that had even more graphics.

The files are all exactly 1716 bytes long and peaking at a hex editor they look to be pretty simple, but I'm not an expert and maybe they hide some complexity.

I've attached [printShopGS.zip](https://github.com/user-attachments/files/16935595/printShopGS.zip) that includes a bunch of sample graphics files and some screenshots of what some of them look like in the program on an emulated Apple IIgs.

**Comment by jsummers** [comment]
The files are easy to decode, but not really possible to identify -- except by the file size, which I don't think is a good enough signal.

I plan to add support for it, but the -m option will be needed to invoke it.

**Comment by Sembiance** [comment]
Totally reasonable approach and that would work perfectly for my uses as I pre-identify these as Print Shop GS files thanks to the ProDOS file system types. So having to invoke with a -m option works great for me.

**Comment by Sembiance** [comment]
Tested out the new module against about 1,100 printshop GS graphics, worked great on all of em. Thanks for adding support for it!
