### ISSUE TITLE
Problematic vort files

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#93]
Found some vort files ([vort_bad.zip](https://github.com/user-attachments/files/17116000/vort_bad.zip)) that don't convert correctly with deark. In the zip are .png files produced by vort2ppm that show how they should work. I also included a vortinfo.txt that shows what `vortinfo <file.pix>` shows.

**Comment by jsummers** [comment]
Thanks for the report.

Apparently, the bits-per-pixel field can't be trusted to mean anything, so other fields must be used to help guess the image type. I'll fix it, or at least make it better.

I don't know what to make of the fact that most of these images appear upside down. The format does not have a field that tells the orientation.

**Comment by Sembiance** [comment]
These particular vort files are applied as textures to polygons in a scene. In that environment being upside down might not matter much, so that's probably correct to render them that way.

https://discmaster.textfiles.com/browse/5566/Ian%20and%20Stuart's%20One%20(Australia).iso/Australasian%20Legends/Community/DECR%20-%20UMelbourne/Vort/Sample%20Scenes/Bedroom

NOTE: They were mis-detected as alias PIX on discmaster1 but are properly detected as vort in the upcoming discmaster2
